/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Kata_Tennis;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.web.servlet.support.SpringBootServletInitializer;

@SpringBootApplication
public class Tennis extends SpringBootServletInitializer {
	
	public static void main(String[] args) {
		SpringApplication.run(Tennis.class, args);
		System.out.println(".........Application Started...........");
	}
	
    public boolean someMethod() {
        return true;
    }
}
